apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9-management # Or a specific version
          ports:
            - containerPort: 5672  # AMQP port
            - containerPort: 15672 # Management UI port
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: myuser
            - name: RABBITMQ_DEFAULT_PASS
              value: mypassword
          #  livenessProbe: # Add livenessProbe
          #    tcpSocket:
          #      port: 5672
          #    initialDelaySeconds: 15
          #    periodSeconds: 10
          # readinessProbe: # Add readinessProbe
          #   tcpSocket:
          #     port: 5672
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management
  type: ClusterIP # Use ClusterIP for internal access within the cluster